### ISSUE TITLE
Support other Formats

### ISSUE THREAD

**Issue by fionera** [vilhalmer/oguri#16]
Hi, 

I just tried oguri and its awesome. Its totally worth the 18GB Ram it would use to load my 388MB Gif which I converted from an Webm, but sadly my Kernel thinks differently. Can you add support to other Video formats like webm?

**Comment by vilhalmer** [comment]
I really wish I could say yes, but the amount of work needed to support any sort of true video format would be basically a different tool by the end. Oguri very specifically trades memory to drive down CPU time, by caching every frame of an animation. With video formats (or even extremely long GIFs), this quickly becomes infeasible.

A viable alternative would be to create a UI for mpv with wlr-layer-shell support. This would provide support for a much wider range of formats, at the expense of making the opposite trade.

**Comment by truesilver92** [comment]
@vilhalmer Any advice or docs to look at for doing an mpv UI with wlr-layer-shell support? I like the low cpu goal of this project, but the limitations in terms of framerate and color depth in gif are too rough.

**Comment by vilhalmer** [comment]
I'm not familiar at all with the mpv codebase, but #mpv-devel on Freenode might be a good place to start. There's also #sway-devel for discussion about implementing wlr protocols.
