### ISSUE TITLE
[Segmentation fault] How use it?

### ISSUE THREAD

**Issue by ZicPL** [vilhalmer/oguri#17]
Hi,
I haven't installed sway yet. How can I use oguri (some tutorial for beginner)? My command in terminal (I'm in ../oguri/build/) `./oguri -c /home/user/Wallpaper/config ` give me back:
**Segmentation fault**
My config is:
```
[output LVDS-1]
image=/home/zic/Wallpaper/background.jpg
filter=nearest
scaling-mode=fill
anchor=center
```

so I look at log:
`sudo tail -f /var/log/syslog`
```
Sep  9 23:47:58 Debian-zic kernel: [20781.071150] oguri[14287]: segfault at 0 ip 00007fe704d54274 sp 00007ffc918334a0 error 4 in libwayland-client.so.0.3.0[7fe704d53000+6000]
Sep  9 23:47:58 Debian-zic kernel: [20781.071156] Code: 29 ac 24 50 01 00 00 0f 29 b4 24 60 01 00 00 0f 29 bc 24 70 01 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 c8 00 00 00 31 c0 <48> 8b 13 4c 8d 6c 24 20 48 8d 4c 24 08 48 8d 84 24 b0 01 00 00 c7
```
but I don't understand what it means..

files in : /home/user/Wallpaper/ : `ls -lah`

> drwxr-xr-x 2 zic zic 4,0K wrz 10 00:16 .
> drwxr-xr-x 7 zic zic 4,0K wrz  9 23:23 ..
> -rwxr-xr-x 1 zic zic 189K wrz  9 02:01 background.jpg
> -rw-r--r-- 1 zic zic   93 wrz 10 00:15 config
> -rw-r--r-- 1 zic zic  24M wrz  9 03:42 matrix.mp4

OS: Debian 10 (Wayland)

**Comment by vilhalmer** [comment]
I’d need a full backtrace of that crash to figure out exactly what’s going on, but I can solve your problem without it. :)

oguri will not work outside of sway or some other wayland compositor, you need to install it and then launch oguri either from the sway config file or by some other method.

I’ll leave this open for now though because it should print a friendly message instead of segfaulting.

**Comment by ZicPL** [comment]
Thx for quick reply. I suspect your addon is great. My mistake was: I wanted to use "oguri" in Mutter .. I had to read about wayland composers (I don't know much about the new protocol). In Gnome, the basic composer is "Mutter". I lost hope about Live Wallpaper in my OS.

_Komorebi_ doesn't work with wayland .. My issiue: [#120](https://github.com/cheesecakeufo/komorebi/issues/179)_

**Comment by vilhalmer** [comment]
Yep, Mutter would have to add support for wlr-layer-shell. Hopefully someday!

**Comment by ZicPL** [comment]
anyway Thank 4 ur help :)
