### ISSUE TITLE
wallpaper gif resources

### ISSUE THREAD

**Issue by AdrienLemaire** [vilhalmer/oguri#21]
Thanks for making oguri, This looks nice!

Do you have suggestions regarding good resources to pick gif wallpapers from? 
I usually find mine on http://wallheaven.cc/ , but they don't seem to share gifs there.  And https://giphy.com/ doesn't seem to offer the possibility to search by resolution.

**Comment by vilhalmer** [comment]
I don't have any particular sources. I mostly use pixel art for mine, as it tends to be a fairly low framerate and thus the least taxing on the CPU (and my attention span). I've found a couple good ones on /r/PixelArt.
