### ISSUE TITLE
Could not open image

### ISSUE THREAD

**Issue by fly1ngDream** [vilhalmer/oguri#22]
![image](https://user-images.githubusercontent.com/44244245/73984800-2ecbd180-4942-11ea-8100-4892248e4c79.png)
![image](https://user-images.githubusercontent.com/44244245/73984957-a00b8480-4942-11ea-8c1e-e0e50357199b.png)
![image](https://user-images.githubusercontent.com/44244245/73984822-3d19ed80-4942-11ea-90cf-c81660e6a936.png)

**Comment by vilhalmer** [comment]
The only thing I can think of filesystem-wise would be a permissions issue. If that’s not the case, mind uploading the image so I can test it on my end?

**Comment by fly1ngDream** [comment]
@vilhalmer i've tried using different gif images and also tried changing image permissions. My system is 5.5.1-arch
![image](https://user-images.githubusercontent.com/44244245/73987298-8f5e0d00-4948-11ea-8974-62a3755d3a1b.png)

**Comment by vilhalmer** [comment]
I just pushed 41d8e32 to improve the error message, hopefully it will shed some light.

**Comment by fly1ngDream** [comment]
![image](https://user-images.githubusercontent.com/44244245/74089563-f72c6900-4aaa-11ea-8db0-1dd5fcc058e2.png)

**Comment by vilhalmer** [comment]
What do you get if you run `file` on the gif? A lot of sites have started hosting mp4 video for files that claim to be gifs to save bandwidth.

**Comment by fly1ngDream** [comment]
`lofi_wallpaper.gif: GIF image data, version 89a, 1920 x 1080`. And yes, this gif is opened using mpv

**Comment by vilhalmer** [comment]
Can you attach it? I'm out of ideas for how to debug this remotely.

**Comment by fly1ngDream** [comment]
I've downloaded it from [here](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallpaperaccess.com%2Ffull%2F723262.gif&f=1&nofb=1)

**Comment by vilhalmer** [comment]
I'm able to load it here. Hmm. The only other thing I can think of is some issue with pixbuf or how oguri is built against it. What's your version of gdk-pixbuf2? Did you build oguri by hand, or are you using the AUR package?

**Comment by fly1ngDream** [comment]
![image](https://user-images.githubusercontent.com/44244245/74089877-6061ab80-4aae-11ea-8ec7-4482f3237952.png)
I use AUR oguri package

**Comment by vilhalmer** [comment]
That gdk-pixbuf from the AUR is incredibly out of date, I wonder if it's being picked up instead of 2.40 when building?

**Comment by fly1ngDream** [comment]
Removed `gdk-pixbuf` and reinstalled `oguri`. The issue remains
![image](https://user-images.githubusercontent.com/44244245/74089989-44123e80-4aaf-11ea-888d-68ccb1f29eda.png)

**Comment by vilhalmer** [comment]
I am at a loss. The only difference in my build output is that pkg-config is `/bin/pkg-config` on my system. Not sure why that would differ between arch installs, but it also shouldn't make any difference. Can you paste `ldd /bin/oguri`? (Please as text instead of a screenshot, it'll make comparing it much easier.

**Comment by fly1ngDream** [comment]
```
linux-vdso.so.1 (0x00007fff8cab8000)
libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f5c0965e000)
libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007f5c09638000)
libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f5c095dc000)
libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007f5c095cc000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f5c095c1000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f5c093fa000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f5c093d6000)
libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f5c0932c000)
libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f5c092e4000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f5c09216000)
libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f5c091de000)
libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f5c091d9000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f5c091ad000)
libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f5c0919d000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f5c09190000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f5c09050000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f5c0903b000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007f5c09021000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f5c08ed9000)
libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f5c08db4000)
libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f5c08daf000)
libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f5c08bff000)
libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f5c08bf4000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5c097d2000)
libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f5c08bc2000)
libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f5c08baf000)
libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f5c08aab000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f5c08aa6000)
libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f5c08a9e000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5c08a99000)
libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f5c08a24000)
libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f5c089c7000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f5c089ae000)
libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f5c08989000)
libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f5c08938000)
```

**Comment by vilhalmer** [comment]
Can you install python-gobject (good chance it's there already) and run this python snippet? It'll output all the extensions that pixbuf should be able to load on your system.
```
from gi.repository import GdkPixbuf
for fmt in GdkPixbuf.Pixbuf.get_formats():
    print(fmt.get_extensions())
```

Something else to try would be loading a jpg or png. That would narrow down whether pixbuf is working at all.

**Comment by fly1ngDream** [comment]
```
['wmf', 'apm']
['ani']
['bmp']
['gif']
['heif', 'heic']
['icns']
['ico', 'cur']
['jp2', 'jpc', 'jpx', 'j2k', 'jpf']
['jpeg', 'jpe', 'jpg']
['png']
['pnm', 'pbm', 'pgm', 'ppm']
['qtif', 'qif']
['svg', 'svgz', 'svg.gz']
['tga', 'targa']
['tiff', 'tif']
['xbm']
['xpm']
```

**Comment by fly1ngDream** [comment]
Error is the same for `jpg` image

**Comment by vilhalmer** [comment]
I don't have a clue what could be wrong, sorry. :(

My last remaining thing to check is whether other software you have which depends on pixbuf is able to load images. I'll leave this open for now in case I think of anything else.

**Comment by vilhalmer** [comment]
Can you upload your oguri binary somewhere? I can try running it on my system to see if it exhibits the same behavior, they should presumably be compatible.

**Comment by fly1ngDream** [comment]
You can download it [here](https://drive.google.com/open?id=12UvS7txm11dv8X05GNdST_tJrxqpgNlG)

**Comment by vilhalmer** [comment]
It's able to load lofi_wallpaper.gif on my system. I'm not sure exactly what this means, but indicates that the problem must be outside oguri itself.

**Comment by fly1ngDream** [comment]
Interesting...

**Comment by vilhalmer** [comment]
If you end up tracking it down please reopen this, I'd love to document/work around/fix whatever it is.

**Comment by fly1ngDream** [comment]
Ill add a comment if find a fix
