### ISSUE TITLE
oguri-swaybg not working

### ISSUE THREAD

**Issue by rhysperry111** [vilhalmer/oguri#24]
Hi, I have added `swaybg_command oguri-swaybg` to my sway config but all i get is a grey backround.

There are no errors in the log so I don't know what the problem is

**Comment by rhysperry111** [comment]
Actually, I believe there is an error. It says:
`Invalid selection type: Image`

**Comment by vilhalmer** [comment]
Indeed, it has been broken for a while. I left it because I was curious if anyone was using it. :)

I will get it fixed up.

**Comment by vilhalmer** [comment]
Fixed in 518baf2.
