### ISSUE TITLE
Flickering between image change when used as swaybg

### ISSUE THREAD

**Issue by rhysperry111** [vilhalmer/oguri#25]
Hi, sorry to create two issues in one day. Now that the previous one was fixed I have found this one.

Basically, when integrated with sway the background seems to flicker in between image changes. The reason I had switched to oguri was because I was led to believe (while reading about this exact same problem with swaybg) that oguri would not flicker.

Is this something that can easily fixed?

**Comment by rhysperry111** [comment]
I believe this is related to #3

**Comment by vilhalmer** [comment]
If you use `oguri-swaybg`, you have the same limitations as the real swaybg. If you want to avoid the flickering, you have to exec oguri yourself and use `ogurictl` to change the image.

**Comment by vilhalmer** [comment]
It's worth nothing that all of this will be documented before I release 1.0. I may also eliminate oguri-swaybg entirely given the limitations.

**Comment by rhysperry111** [comment]
Ok, thank you. I am going to have to modify my PR of https://github.com/adi1090x/battery-wallpaper as it is based on swaybg (I did not know of this limitation when I wrote it.

**Comment by vilhalmer** [comment]
It would be possible to rewrite `oguri-swaybg` to call `ogurictl` but since you would still have to run oguri separately I don't think it's worth it.

**Comment by vilhalmer** [comment]
I would accept a PR doing so though!
