### ISSUE TITLE
How do I make the oguri deamon run in background?

### ISSUE THREAD

**Issue by snakedye** [vilhalmer/oguri#29]
I'd like to run https://github.com/adi1090x/dynamic-wallpaper on swaywm. I read to the readme but I still have no idea how to use it.

_Sent from my OnePlus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vilhalmer** [comment]
The easiest way would be to just add `exec oguri` to your sway config. You'll probably also want to add `swaybg_command -` to prevent the default swaybg from running.

**Comment by snakedye** [comment]
Thanks
