### ISSUE TITLE
Drawing Multiple Images

### ISSUE THREAD

**Issue by muevoid** [vilhalmer/oguri#32]
Hello! First of all thank you for this I really enjoy it. However one issue I have found is when using ogurictl after looking at the code from what I understand instead of drawing the new image then getting rid of the last one it seems you just keep drawing the new image over the new one. This wouldn't be an issue but if you switch wallpapers a lot(like a wallpaper switcher or something). It leads to very high memory usage.

**Comment by vilhalmer** [comment]
It's designed to recreate the buffer ring each time you switch images, so you should end up with exactly one buffer per frame per output. That said, I haven't run it through valgrind in a while so it's possible I'm leaking frames by accident.

**Comment by muevoid** [comment]
It is for sure leaking memory. Switching images around 10 times for me increases usage from like 100mb to 500mb. And this is with static images of the same resolution.

**Comment by vilhalmer** [comment]
I spent some quality time with valgrind and I think you will find things at least 99% less leaky after 271bf11..d6f195a.

Definitely reopen this if you still see issues. Thanks for the report!
