### ISSUE TITLE
running from a crontab

### ISSUE THREAD

**Issue by epsilon-0** [vilhalmer/oguri#35]
It seems that running oguri from a crontab results in a socket not found error
```
Unable to connect to oguri socket: No such file or directory
```

I am not sure what this means.

**Comment by vilhalmer** [comment]
My guess is that `$XDG_RUNTIME_DIR` isn't set for the cronjob. Currently there's no way to hardcode the path, though that's on my todo list. You could export it to the correct value in the cron config, though.

(Also I'm assuming you mean `ogurictl` here and not oguri itself.)

**Comment by epsilon-0** [comment]
Yes, that is what I meant, thanks a lot!.
