### ISSUE TITLE
Image filenames with spaces cause errors

### ISSUE THREAD

**Issue by ArenM** [vilhalmer/oguri#37]
When using `ogurictl` with an image that has a space in the filename it outputs `Invalid configuration`, and `oguri` outputs `[ipc:2] Failed to parse property 'image'`.

There is a workaround to this which is to add escaped quotes to the filename, such as `ogurictl output --image \"/tmp/with\ space.jpg\" '*'` instead of `ogurictl output --image /tmp/with\ space.jpg '*'`.

**Comment by vilhalmer** [comment]
I tracked this down today, `wordexp` is behaving more like a shell than I wanted it to. Just need to decide on a fix.
