### ISSUE TITLE
Question: is ogurictl output * supported?

### ISSUE THREAD

**Issue by hexive** [vilhalmer/oguri#41]
[Issue 31](https://github.com/vilhalmer/oguri/issues/31) mentions a case where `ogurictl output * --image whatever.png` doesn't override the config file value if it is set.

But I have config output value set as
```
[output *]
```
and I'm not able to change images with `ogurictl output * --image whatever.png`

My images change as expected with a specific output `ogurictl output eDP-1 --image whatever.png`

***
I'm using oguri in a small dynamic wallpaper script so it would be nice to be able to set wallpapers with * instead of trying to figure out what displays are available.

Thanks for your help.

**Comment by vilhalmer** [comment]
Are you escaping the asterisk in your shell so it isn't being interpreted as a list of files? (i.e. `'*'` or `\*`)

**Comment by hexive** [comment]
I wasn't, but I just tried both in a bash shell, zsh and fish for fun haha ... no luck.

```
ogurictl output \* --image /home/g/sunpaper/images/The-Beach/1.jpg
ogurictl output '*' --image /home/g/sunpaper/images/The-Beach/1.jpg 
```

I'm using ogurictl -V 1.0 from AUR

**Comment by hexive** [comment]
I apologize, after some more testing I can confirm escaping the characters was the fix for me.

Even though I had `[output *]` in the config file, I was trying to change output that was already set explicitly in ogurictl like:

`ogurictl output eDP-1 --image whatever.png`
with
`ogurictl output \* --image whatever.png`

So I guess that doesn't work for the same reason as [#31](https://github.com/vilhalmer/oguri/issues/31)

Thanks again for your time.
