### ISSUE TITLE
Build issue on Fedora 34

### ISSUE THREAD

**Issue by terrarier2111** [vilhalmer/oguri#42]
Hello, today i found this great repository and tried to use and therefore build it, but during the building process i encountered a strange issue, despite cairo (cairo-1.17.4-3.fc34.x86_64) being already installed i received this: 
`Build type: native build
Project name: oguri
Project version: 1.0.0
C compiler for the host machine: cc (gcc 11.1.1 "cc (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1)")
C linker for the host machine: cc ld.bfd 2.35.1-41
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency cairo found: NO (tried pkgconfig)

meson.build:14:0: ERROR: Dependency "cairo" not found, tried pkgconfig`

**Comment by vilhalmer** [comment]
I don't use Fedora but I would guess you need the `cairo-devel` package (and probably any other devel variants as well).

**Comment by terrarier2111** [comment]
Thx it worked with the only problem being neither wayland-client nor wayland-client-devel being available.

**Comment by vilhalmer** [comment]
Google suggests it's called libwayland-client-devel.

**Comment by terrarier2111** [comment]
Doesn't exist either sadly

**Comment by vilhalmer** [comment]
Playing guess and check for a distro I know nothing about is unproductive for both of us. Fedora's support channels can probably point you in the right direction, or you could examine the build dependencies for a Fedora package of some other wayland tool.
